function init(self)                                 -- [1]
	msg.post(".", "acquire_input_focus")            -- [2]

	self.moving = false                             -- [3]
	self.input = vmath.vector3()                    -- [4]
	self.dir = vmath.vector3(0, 1, 0)               -- [5]
	self.speed = 50      

	local json = require("json")
	
end

function final(self)                                -- [7]
	msg.post(".", "release_input_focus")            -- [8]
end

function update(self, dt)                           -- [9]
	if self.moving then
		local pos = go.get_position()               -- [10]
		pos = pos + self.dir * self.speed * dt      -- [11]
		go.set_position(pos)  
		
	elseif self.direcao == "andandocima" then sprite.play_flipbook("/Heroi#sprite", "cima")
	elseif self.direcao == "andandobaixo" then sprite.play_flipbook("/Heroi#sprite", "baixo")
	elseif self.direcao == "andandoesquerda" then sprite.play_flipbook("/Heroi#sprite", "esquerda")
	elseif self.direcao == "andandodireita" then sprite.play_flipbook("/Heroi#sprite", "direita")
	end

	self.input.x = 0                                -- [13]
	self.input.y = 0
	self.moving = false
	self.itemColetado = nil


	
	
end

function on_input(self, action_id, action)          -- [14]
	if action_id == hash("ircima") then
		self.direcao = "andandocima"
		if (self.direcao ~= self.direcaoanterior) then sprite.play_flipbook("/Heroi#sprite", "cima") end
		self.direcaoanterior = self.direcao
		self.input.y = 1  
	elseif action_id == hash("irbaixo") then
		self.direcao = "andandobaixo"
		if (self.direcao ~= self.direcaoanterior) then sprite.play_flipbook("/Heroi#sprite", "baixo") end
		self.direcaoanterior = self.direcao
		self.input.y = -1
	elseif action_id == hash("iresquerda") then
		self.direcao = "andandoesquerda"
		if (self.direcao ~= self.direcaoanterior) then sprite.play_flipbook("/Heroi#sprite", "esquerda") end
		self.direcaoanterior = self.direcao
		self.input.x = -1
	elseif action_id == hash("irdireita") then
		self.direcao = "andandodireita"
		if (self.direcao ~= self.direcaoanterior) then sprite.play_flipbook("/Heroi#sprite", "direita") end
		self.direcaoanterior = self.direcao
		self.input.x = 1

	elseif action_id == hash("soltar") then
		pos = go.get_position("/Heroi")
		x = (self.dir.x * 30)
		y = (self.dir.y * 30)
		pos = vmath.vector3(pos.x+x,pos.y+y,0.5)
		if(itemColetado ~= nil) then
		go.set(itemColetado, "position", pos)
		itemColetado = nil
		msg.post("/MenuHeroi#MenuHeroi", 'itemAlterado', {item=''}) 
		end
	end

	if vmath.length(self.input) > 0 then
		self.moving = true                          -- [16]
		self.dir = vmath.normalize(self.input)      -- [17]
	end
end




function on_message(self, message_id, message, sender)
	-- Handle collision
	if message_id == hash("contact_point_response") then
		local newpos = go.get_position() + message.normal * message.distance
		colisao = tostring(message.other_id)
		if(string.find(colisao, "Item") ~= nil) then
			if(itemColetado ~= nil) then return 0 end
			item = string.sub(colisao, 8,-2)
			go.set(item, "position", vmath.vector3(100,100,0))
			itemColetado = item
			msg.post("/MenuHeroi#MenuHeroi", 'itemAlterado', {item=item}) 
			return 0 end


			if(string.find(colisao, "Instrucao") ~= nil) then
				colID = string.sub(colisao, 9,-2)
				local tjf = json.decode(sys.load_resource("/Interface/Instrucoes.json"))
				msg.post("/MenuHeroi#MenuHeroi", 'mostrarInstrucao', {instrucao=tjf[colID]}) 
				end
			
		go.set_position(newpos)
	end
end