function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	local interface = gui.get_node('Item')                           -- [6]
	gui.set_text(interface,"")
	gui.set_enabled(gui.get_node('Instrucoes'), false)
	gui.set_enabled(gui.get_node('FundoInstrucoes'), false)
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/ script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if (message_id == hash("itemAlterado")) then
		gui.set_text(gui.get_node('Item'),message.item)
	end

	if (message_id == hash("mostrarInstrucao")) then
		gui.set_text(gui.get_node('Instrucoes'),message.instrucao)
		gui.set_enabled(gui.get_node('Instrucoes'), true)
		gui.set_enabled(gui.get_node('FundoInstrucoes'), true)
	end

	
	if (message_id == hash("mostrarInstrucao")) then
		gui.set_text(gui.get_node('Instrucoes'),message.instrucao)
		gui.set_enabled(gui.get_node('Instrucoes'), true)
		gui.set_enabled(gui.get_node('FundoInstrucoes'), true)
	end
	
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
